apiVersion: apps/v1
kind: Deployment
metadata:
  name: martin-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: martin-notifications
  template:
    metadata:
      labels:
        app: martin-notifications
    spec:
      containers:
        - name: martin-notifications
          image: addsomebass/martin-notifications:3
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: martin-notifications
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort